const { User } = require("../models/User");
const { verifyAccessToken } = require("../utils/authTokens");
const ADMIN_ROLE_NAMES = new Set(["admin", "superadmin", "أدمن"]);
const EMPLOYEE_ROLE_NAMES = new Set(["employee", "worker", "موظف", "عامل"]);
const getBearerToken = (req) => { const authorization = req.headers.authorization; if (!authorization?.startsWith("Bearer ")) return null; return authorization.slice(7).trim(); };
const authenticate = async (req) => { const token = getBearerToken(req); if (!token) throw Object.assign(new Error(req.t("auth.noToken")), { statusCode: 401, code: "ACCESS_TOKEN_MISSING" }); let payload; try { payload = verifyAccessToken(token); } catch (error) { const isExpired = error?.name === "TokenExpiredError"; throw Object.assign(new Error(req.t(isExpired ? "auth.tokenExpired" : "auth.invalidToken")), { statusCode: 401, code: isExpired ? "ACCESS_TOKEN_EXPIRED" : "ACCESS_TOKEN_INVALID" }); } const user = await User.findById(payload.id).populate("role"); if (!user || user.isDeleted || !user.isActive) throw Object.assign(new Error(req.t("auth.unavailable")), { statusCode: 401, code: "ACCOUNT_UNAVAILABLE" }); req.user = { id: user._id.toString(), username: user.username, role: user.role }; };
const sendAuthError = (res, error) => res.status(error.statusCode || 401).json({ message: error.message, ...(error.code ? { code: error.code } : {}) });
function verifyToken(req, res, next) { authenticate(req).then(next).catch((error) => sendAuthError(res, error)); }
function verifyTokenAndAdmin(req, res, next) { authenticate(req).then(() => { const roleName = String(req.user.role?.name || "").trim().toLowerCase(); if (!ADMIN_ROLE_NAMES.has(roleName)) return res.status(403).json({ message: req.t("auth.adminOnly") }); next(); }).catch((error) => sendAuthError(res, error)); }
function verifyTokenAndEmployee(req, res, next) { authenticate(req).then(() => { const roleName = String(req.user.role?.name || "").trim().toLowerCase(); if (!EMPLOYEE_ROLE_NAMES.has(roleName)) return res.status(403).json({ message: req.t("auth.employeeOnly") }); next(); }).catch((error) => sendAuthError(res, error)); }
function verifyTokenAndOnlyUser(req, res, next) { authenticate(req).then(() => { if (req.user.id !== req.params.id) return res.status(403).json({ message: req.t("auth.selfOnly") }); next(); }).catch((error) => sendAuthError(res, error)); }
function verifyTokenAndAuthorization(req, res, next) { authenticate(req).then(() => { const roleName = String(req.user.role?.name || "").trim().toLowerCase(); const isAdmin = ADMIN_ROLE_NAMES.has(roleName); if (req.user.id !== req.params.id && !isAdmin) return res.status(403).json({ message: req.t("auth.selfOrAdmin") }); next(); }).catch((error) => sendAuthError(res, error)); }
module.exports = { verifyToken, verifyTokenAndAdmin, verifyTokenAndEmployee, verifyTokenAndOnlyUser, verifyTokenAndAuthorization };
