const messages = {
  en: {
    "common.routeNotFound": "Route not found", "common.serverError": "An unexpected server error occurred",
    "validation.required": "{{field}} is required", "validation.stringMin": "{{field}} must be at least {{limit}} characters", "validation.stringMax": "{{field}} must not exceed {{limit}} characters", "validation.numberMin": "{{field}} must be at least {{limit}}", "validation.number": "{{field}} must be a number", "validation.integer": "{{field}} must be a whole number", "validation.invalid": "Invalid value for {{field}}",
    "auth.emailExists": "Email already exists", "auth.customerRoleMissing": "Customer role is not configured", "auth.registerSuccess": "Account created successfully", "auth.invalidCredentials": "Invalid email or password", "auth.inactive": "Account is inactive", "auth.loginSuccess": "Login successful", "auth.userNotFound": "User not found", "auth.noToken": "No token provided, access denied", "auth.invalidToken": "Invalid token, access denied", "auth.tokenExpired": "Access token has expired", "auth.refreshRequired": "Refresh token is required", "auth.refreshInvalid": "Refresh token is invalid or expired", "auth.refreshSuccess": "Session refreshed successfully", "auth.unavailable": "Account is inactive or unavailable", "auth.adminOnly": "Access denied. Admin role is required", "auth.selfOnly": "Access denied. You can only access your own account", "auth.selfOrAdmin": "Access denied. Only the account owner or an admin is allowed", "auth.employeeOnly": "Access denied. Employee role is required",
    "users.usernameExists": "Username already exists", "users.invalidRole": "Invalid role ID", "users.updateForbidden": "You are not allowed to update this user", "users.deleted": "User deleted successfully",
    "orders.duplicateMaterial": "Each raw material can only be selected once per order", "orders.materialUnavailable": "One or more raw materials are unavailable", "orders.insufficientStock": "Insufficient stock for {{material}}", "orders.stockChanged": "Raw material stock changed. Please review your quantities", "orders.notFound": "Order not found", "orders.invalidId": "Invalid order ID", "orders.notEditable": "Only pending orders can be edited", "orders.updated": "Order updated successfully", "orders.assignmentRequired": "Employee and expected finish date are required", "orders.employeeUnavailable": "Selected employee is unavailable", "orders.notEmployee": "Selected user is not an employee", "orders.invalidTransition": "Invalid status transition from {{from}} to {{to}}", "orders.startRequirements": "Assign an employee and expected finish date before starting production", "orders.reservedUnavailable": "Reserved stock is no longer available", "orders.stageCompletionUnavailable": "This order stage cannot be reported as completed", "orders.stageCompletionExists": "A completion request is already pending for this stage", "orders.stageCompletionRequested": "Stage completion was sent to the admin for review", "orders.stageCompletionNotFound": "Stage completion request not found", "orders.stageCompletionReviewed": "This stage completion request was already reviewed", "orders.stageCompletionOutdated": "This completion request does not match the order's current stage or employee", "orders.stageCompletionApproved": "Stage completion approved", "orders.stageCompletionRejected": "Stage completion rejected", "orders.deliveryEmployeeRequired": "Assign a delivery employee before starting the delivery stage", "orders.deliveryCompletionRequired": "Delivery must be completed by the assigned delivery employee and approved by an admin", "orders.deleted": "Order deleted successfully",
    "raw.notFound": "Raw material not found", "raw.reservedExceedsStock": "Reserved quantity cannot exceed stock quantity", "raw.deleteBlocked": "Raw material has reserved stock and cannot be deleted", "raw.deleted": "Raw material deleted successfully", "raw.nameNoDigits": "Raw material name cannot contain numbers", "raw.singleColorOnly": "Only one color can be saved when editing a raw material",
    "expenses.notFound": "Expense not found", "expenses.deleted": "Expense deleted successfully",
    "roles.notFound": "Role not found", "roles.exists": "Role already exists", "roles.created": "Role created successfully", "roles.updated": "Role updated successfully", "roles.deleted": "Role deleted successfully"
  },
  ar: {
    "common.routeNotFound": "المسار غير موجود", "common.serverError": "حدث خطأ غير متوقع في الخادم",
    "validation.required": "حقل {{field}} مطلوب", "validation.stringMin": "يجب ألا يقل حقل {{field}} عن {{limit}} محارف", "validation.stringMax": "يجب ألا يتجاوز حقل {{field}} {{limit}} محارف", "validation.numberMin": "يجب ألا تقل قيمة {{field}} عن {{limit}}", "validation.number": "يجب أن تكون قيمة {{field}} رقمًا", "validation.integer": "يجب أن تكون قيمة {{field}} عددًا صحيحًا", "validation.invalid": "قيمة غير صالحة للحقل {{field}}",
    "auth.emailExists": "البريد الإلكتروني مستخدم بالفعل", "auth.customerRoleMissing": "دور الزبون غير مهيأ في النظام", "auth.registerSuccess": "تم إنشاء الحساب بنجاح", "auth.invalidCredentials": "البريد الإلكتروني أو كلمة المرور غير صحيحة", "auth.inactive": "الحساب غير فعال", "auth.loginSuccess": "تم تسجيل الدخول بنجاح", "auth.userNotFound": "المستخدم غير موجود", "auth.noToken": "لم يتم إرسال رمز الدخول، تم رفض الوصول", "auth.invalidToken": "رمز الدخول غير صالح، تم رفض الوصول", "auth.tokenExpired": "انتهت صلاحية رمز الدخول", "auth.refreshRequired": "رمز تجديد الجلسة مطلوب", "auth.refreshInvalid": "رمز تجديد الجلسة غير صالح أو منتهي الصلاحية", "auth.refreshSuccess": "تم تجديد الجلسة بنجاح", "auth.unavailable": "الحساب غير فعال أو غير متاح", "auth.adminOnly": "غير مسموح بالدخول، صلاحية الأدمن مطلوبة", "auth.selfOnly": "غير مسموح، يمكنك الوصول إلى حسابك فقط", "auth.selfOrAdmin": "غير مسموح، الوصول متاح لصاحب الحساب أو الأدمن فقط", "auth.employeeOnly": "غير مسموح بالدخول، صلاحية الموظف مطلوبة",
    "users.usernameExists": "اسم المستخدم مستخدم بالفعل", "users.invalidRole": "معرّف الدور غير صالح", "users.updateForbidden": "غير مسموح لك بتعديل هذا المستخدم", "users.deleted": "تم حذف المستخدم بنجاح",
    "orders.duplicateMaterial": "لا يمكن اختيار المادة الخام نفسها أكثر من مرة في الطلب", "orders.materialUnavailable": "مادة خام واحدة أو أكثر غير متاحة", "orders.insufficientStock": "المخزون غير كافٍ للمادة {{material}}", "orders.stockChanged": "تغيّر مخزون المواد الخام، يرجى مراجعة الكميات", "orders.notFound": "الطلب غير موجود", "orders.invalidId": "معرّف الطلب غير صالح", "orders.notEditable": "يمكن تعديل الطلب فقط عندما يكون قيد الانتظار", "orders.updated": "تم تحديث الطلب بنجاح", "orders.assignmentRequired": "الموظف وتاريخ الانتهاء المتوقع مطلوبان", "orders.employeeUnavailable": "الموظف المحدد غير متاح", "orders.notEmployee": "المستخدم المحدد ليس موظفًا", "orders.invalidTransition": "لا يمكن نقل حالة الطلب من {{from}} إلى {{to}}", "orders.startRequirements": "عيّن موظفًا وتاريخ انتهاء متوقع قبل بدء الإنتاج", "orders.reservedUnavailable": "المخزون المحجوز لم يعد متاحًا", "orders.stageCompletionUnavailable": "لا يمكن إرسال انتهاء هذه المرحلة للمراجعة", "orders.stageCompletionExists": "يوجد طلب إنهاء قيد المراجعة لهذه المرحلة بالفعل", "orders.stageCompletionRequested": "تم إرسال انتهاء المرحلة إلى الأدمن للمراجعة", "orders.stageCompletionNotFound": "طلب إنهاء المرحلة غير موجود", "orders.stageCompletionReviewed": "تمت مراجعة طلب إنهاء المرحلة مسبقًا", "orders.stageCompletionOutdated": "طلب إنهاء المرحلة لا يطابق مرحلة الطلب أو الموظف الحالي", "orders.stageCompletionApproved": "تم اعتماد انتهاء المرحلة", "orders.stageCompletionRejected": "تم رفض انتهاء المرحلة", "orders.deliveryEmployeeRequired": "يجب تعيين موظف مسؤول عن التسليم قبل بدء مرحلة التسليم", "orders.deliveryCompletionRequired": "يجب أن ينهي موظف التسليم المسؤول مرحلة التسليم ثم يعتمدها الأدمن", "orders.deleted": "تم حذف الطلب بنجاح",
    "raw.notFound": "المادة الخام غير موجودة", "raw.reservedExceedsStock": "لا يمكن أن تتجاوز الكمية المحجوزة كمية المخزون", "raw.deleteBlocked": "لا يمكن حذف المادة الخام لوجود كمية محجوزة منها", "raw.deleted": "تم حذف المادة الخام بنجاح", "raw.nameNoDigits": "اسم المادة الخام لا يمكن أن يحتوي على أرقام", "raw.singleColorOnly": "عند تعديل مادة خام موجودة يمكن حفظ لون واحد فقط",
    "expenses.notFound": "المصروف غير موجود", "expenses.deleted": "تم حذف المصروف بنجاح",
    "roles.notFound": "الدور غير موجود", "roles.exists": "الدور موجود بالفعل", "roles.created": "تم إنشاء الدور بنجاح", "roles.updated": "تم تحديث الدور بنجاح", "roles.deleted": "تم حذف الدور بنجاح"
  }
};

const fieldLabels = {
  en: { firstName: "First name", lastName: "Last name", email: "Email", phoneNumber: "Phone number", username: "Username", password: "Password", confirmPassword: "Password confirmation", role: "Role", salary: "Salary", description: "Description", notes: "Notes", rawMaterials: "Raw materials", rawMaterialId: "Raw material", quantity: "Quantity", employee: "Employee", expectedFinishDate: "Expected finish date", title: "Title", category: "Category", amount: "Amount", date: "Date", name: "Name", stockQuantity: "Stock quantity", reservedQuantity: "Reserved quantity", unitPrice: "Unit price", minimumStock: "Minimum stock", status: "Status", address: "Address" },
  ar: { firstName: "الاسم الأول", lastName: "الاسم الأخير", email: "البريد الإلكتروني", phoneNumber: "رقم الموبايل", username: "اسم المستخدم", password: "كلمة المرور", confirmPassword: "تأكيد كلمة المرور", role: "الدور", salary: "الراتب", description: "الوصف", notes: "الملاحظات", rawMaterials: "المواد الخام", rawMaterialId: "المادة الخام", quantity: "الكمية", employee: "الموظف", expectedFinishDate: "تاريخ الانتهاء المتوقع", title: "العنوان", category: "التصنيف", amount: "المبلغ", date: "التاريخ", name: "الاسم", stockQuantity: "كمية المخزون", reservedQuantity: "الكمية المحجوزة", unitPrice: "سعر الوحدة", minimumStock: "الحد الأدنى للمخزون", status: "الحالة", address: "العنوان" }
};

const normalizeLanguage = (value = "") => String(value).toLowerCase().startsWith("en") ? "en" : "ar";
const interpolate = (text, params = {}) => Object.entries(params).reduce((value, [key, item]) => value.replaceAll(`{{${key}}}`, String(item)), text);
const translate = (language, key, params = {}) => interpolate(messages[language]?.[key] || messages.en[key] || key, params);
const languageMiddleware = (req, res, next) => { req.language = normalizeLanguage(req.get("Accept-Language")); req.t = (key, params) => translate(req.language, key, params); res.setHeader("Content-Language", req.language); next(); };
const localizeJoiError = (req, error) => { const detail = error?.details?.[0]; const rawField = detail?.path?.[detail.path.length - 1] || "field"; const field = fieldLabels[req.language]?.[rawField] || rawField; const limit = detail?.context?.limit; if (detail?.type === "any.required") return req.t("validation.required", { field }); if (detail?.type === "string.min") return req.t("validation.stringMin", { field, limit }); if (detail?.type === "string.max") return req.t("validation.stringMax", { field, limit }); if (detail?.type === "string.pattern.base" && rawField === "name") return req.t("raw.nameNoDigits"); if (detail?.type === "string.pattern.base" && rawField === "color") return req.t("raw.singleColorOnly"); if (detail?.type === "number.min") return req.t("validation.numberMin", { field, limit }); if (detail?.type === "number.base") return req.t("validation.number", { field }); if (detail?.type === "number.integer") return req.t("validation.integer", { field }); return req.t("validation.invalid", { field }); };
const localizedError = (req, key, statusCode = 400, params = {}) => Object.assign(new Error(req.t(key, params)), { statusCode });
module.exports = { languageMiddleware, localizeJoiError, localizedError, normalizeLanguage, translate };
